# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YnaEnrichment',
            fields=[
                ('Type', models.CharField(db_column='Type', max_length=50, primary_key=True, serialize=False)),
                ('pro_en', models.TextField(db_column='Pro_en')),
                ('pro_de', models.TextField(db_column='Pro_de')),
                ('cod_en', models.TextField(db_column='Cod_en')),
                ('cod_de', models.TextField(db_column='Cod_de')),
            ],
            options={
                'db_table': 'YNA_Enrichment',
                'managed': False,
            },
        ),
    ]
